### ISSUE TITLE
AttributeError for 'sqlalchemy_redshift.dialect' has no attribute 'GEOMETRY'

### ISSUE THREAD

**Issue by jonastim** [great-expectations/great_expectations#7420]
**Describe the bug**
Getting an attribute error when importing GE into my application because of a missing field in `'sqlalchemy_redshift.dialect`. 
`sqlalchemy-redshift` is pulled into the application as a transitive dependency of another library and not actively used.
Exceptions for importing in GE are expected but only `ImportError` and `KeyError` [are caught](https://github.com/great-expectations/great_expectations/blob/6337648fc292b56eb56be0b31a1f61f15c8a654f/great_expectations/self_check/util.py#L374).

```
    import great_expectations as ge
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context/__init__.py", line 4, in <module>
    from great_expectations.data_context.data_context.base_data_context import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/data_context/data_context/base_data_context.py", line 108, in <module>
    from great_expectations.render.renderer.site_builder import SiteBuilder
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/render/renderer/__init__.py", line 2, in <module>
    from .column_section_renderer import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/render/renderer/column_section_renderer.py", line 13, in <module>
    from great_expectations.render.renderer.content_block import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/render/renderer/content_block/__init__.py", line 1, in <module>
    from great_expectations.render.renderer.content_block.validation_results_table_content_block import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/render/renderer/content_block/validation_results_table_content_block.py", line 7, in <module>
    from great_expectations.expectations.core.expect_column_kl_divergence_to_be_less_than import (  # noqa: F401
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/expectations/core/__init__.py", line 1, in <module>
    from .expect_column_distinct_values_to_be_in_set import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/expectations/core/expect_column_distinct_values_to_be_in_set.py", line 8, in <module>
    from great_expectations.expectations.expectation import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/expectations/expectation.py", line 82, in <module>
    from great_expectations.self_check.util import (
  File "/code/venvs/venv/lib/python3.8/site-packages/great_expectations/self_check/util.py", line 352, in <module>
    "GEOMETRY": redshifttypes.GEOMETRY,
AttributeError: module 'sqlalchemy_redshift.dialect' has no attribute 'GEOMETRY'
```
The issue is that with `sqlalchemy-redshift` present in the venv, GE assumes that is going to be used for GE. As none of the versions restrictions ([like here](https://github.com/great-expectations/great_expectations/blob/5dde359202db87a1b485e3565971787702734bbe/reqs/requirements-dev-redshift.txt#L2)) are enforced it's easy for the self-test to fail.

**To Reproduce**
I am seeing this issue with `sqlalchemy-redshift==0.8.2` but not with `sqlalchemy-redshift==0.8.9`.

**Expected behavior**
Have less strict self-tests, e.g. catch `AttributeError`s and emit logs instead of blowing up.  

**Environment**
 - Operating System: Ubuntu 18.04
 - Great Expectations Version: tested with 0.15.40 and 0.14.3 but also expected to happen in the latest version as the exception isn't caught in the current source code (can't test latest version because of numpy clashes)

**Comment by alexsherstinsky** [comment]
@jonastim Thank you for reporting this issue.  Is `sqlalchemy-redshift==0.8.12` by chance available?  Are you able to upgrade to at least the version `sqlalchemy-redshift==0.8.9`, which appears to be working on Ubuntu 18.04?  Thank you.

**Comment by jonastim** [comment]
I've worked around this on my end by adding `sqlalchemy-redshift>=0.8.9` as a dependency to the monitoring library which GE gets imported to. 
The lower version of `sqlalchemy-redshift` is specified in a base layer of a Docker image that would be difficult to change. 
Ideally, I don't want to include this dependency as it isn't used in all environments that the monitoring library is applied to (only the ones extending the particular Docker base image). 
More generally beyond my particular situation I think relaxing the self-check would be reasonable as the version of optional dependencies can't be enforced by GE in all cases.
