### ISSUE TITLE
[BUGFIX] 1.17 breaks SQLAlchemy 1.4 compatibility: AttributeError: module 'sqlalchemy' has no attribute 'Select'

### ISSUE THREAD

**Issue by ranophoenix** [great-expectations/great_expectations#11875]
**Describe the bug**

great-expectations 1.17.0 introduced a reference to `sa.Select` (the SQLAlchemy 2.0-only top-level attribute) in `great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py` via [#11828](https://github.com/great-expectations/great_expectations/pull/11828) ("Fix SingleStoreDB expectations").

In SQLAlchemy 1.4, `Select` is not exposed as a top-level attribute on the `sqlalchemy` module — it lives at `sqlalchemy.sql.expression.Select` (or `sqlalchemy.sql.Select`). Any user still on SQLAlchemy 1.4 hits the following at evaluation time of `expect_column_values_to_be_unique` (or any expectation that resolves the `column_values.unique.condition` metric):

```
AttributeError: module 'sqlalchemy' has no attribute 'Select'. Did you mean: 'select'?
```

This appears to be an unintentional regression — SQLAlchemy 1.4 is still officially supported per `reqs/requirements-dev-sqlalchemy1.txt` (`sqlalchemy<2.0.0`, comment: *"Used to construct the extras_requires dict in setup.py for sqlalchemy dialects that are not yet compatible with sqlalchemy 2.x"*) and `setup.py`'s `sqla1x_only_keys` (clickhouse, redshift, teradata).

**To Reproduce**

```python
# Python 3.12, SQLAlchemy 1.4.x, great-expectations 1.17.0+
import great_expectations as gx
context = gx.get_context()
# ... configure any SQL-backed datasource (Snowflake, Postgres, MySQL, etc.)
# Run a suite containing expect_column_values_to_be_unique
# Result: MetricResolutionError wrapping AttributeError on sa.Select
```

Full traceback excerpt:

```
File ".../great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py", line 89, in _sqlalchemy_window
    from_clause = _table.subquery() if isinstance(_table, sa.Select) else _table
                                                          ^^^^^^^^^
AttributeError: module 'sqlalchemy' has no attribute 'Select'. Did you mean: 'select'?

The above exception was the direct cause of the following exception:

great_expectations.exceptions.exceptions.MetricResolutionError: module 'sqlalchemy' has no attribute 'Select'
```

**Expected behavior**

`expect_column_values_to_be_unique` (and other expectations using `column_values.unique.condition`) should continue to work on SQLAlchemy 1.4, which is still officially supported.

**Environment**

 - Operating System: Linux (containerized Airflow worker)
 - Great Expectations Version: 1.17.0 and 1.17.1 (introduced in 1.17.0)
 - SQLAlchemy Version: 1.4.54
 - Data Source: Snowflake (via snowflake-sqlalchemy 1.9.0)
 - Cloud environment: Airflow on Kubernetes

**Additional context**

The compatibility module `great_expectations.compatibility.sqlalchemy` already exposes a version-safe `Select`, imported from `sqlalchemy.sql.expression`:

```python
try:
    from sqlalchemy.sql.expression import Select
except (ImportError, AttributeError):
    Select = SQLALCHEMY_NOT_IMPORTED
```

The fix is to import `Select` from there in `column_values_unique.py` and replace the two `sa.Select` references (lines 68 and 89). This matches the project's existing compatibility convention (`"Please do not import sqlalchemy directly, import from great_expectations.compatibility.sqlalchemy instead."` per `pyproject.toml`).

Happy to submit a PR.

Last unaffected release: **1.16.1**.
